services:
  postgres:
    image: postgres:15.10
    container_name: mes-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mes
      POSTGRES_PASSWORD: mes
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../../postgres-init:/docker-entrypoint-initdb.d:ro

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: mes-zookeeper
    ports:
     - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: mes-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: mes-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: mes-kafka:9092

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: mes-kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash","-lc"]
    command: >
      "
      echo 'waiting for kafka...' &&
      cub kafka-ready -b kafka:9092 1 60 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic rfid.raw --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic rfid.normalized --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic mes.domain.events --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic integration.erp.inbound --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic integration.erp.outbox --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic dlq --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic mes.logs --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic site.telemetry.raw --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic production.result --partitions 1 --replication-factor 1 &&
      echo 'topics ready'
      "

volumes:
  pg_data:
